<robot xmlns:xacro="http://wiki.ros.org/xacro">
<xacro:macro name="suspension" params="prefix:='' material flip:=false mechanical:=${xacro.load_yaml('$(find sirius_description)/config/mechanical.yaml')} collisions:=${xacro.load_yaml('$(find sirius_description)/urdf/sirius/collisions.yaml')} inertial:=${xacro.load_yaml('$(find sirius_description)/config/inertial/suspension.yaml')}">
  <xacro:property name="_prefix" value="${prefix + '_' if prefix else ''}"/>
  <link name="${_prefix}suspension">
    <visual>    
      <material name="${material}"/>
      <geometry>
        <mesh filename="package://sirius_description/meshes/sirius/suspension.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 ${pi if flip else 0}" />
    </visual>
    <inertial>
      <mass value="${inertial['suspension_mass']}"/>
      <inertia ixx="${inertial['suspension_inertia']['ixx']}" ixy="${inertial['suspension_inertia']['ixy']}" ixz="${inertial['suspension_inertia']['ixz']}" iyy="${inertial['suspension_inertia']['iyy']}" iyz="${inertial['suspension_inertia']['iyz']}" izz="${inertial['suspension_inertia']['izz']}"/>
    </inertial>
    <collision>    
      <geometry>
        <box size="${collisions['suspension_width']} ${collisions['suspension_thickness']} ${collisions['suspension_length']}"/>
      </geometry>
      <origin xyz="${(1 - 2 * flip) * (mechanical['wheel_base']/4 - mechanical['suspension_separation_x']/4 + collisions['suspension_x_shift'])} 0 ${-mechanical['suspension_height']/2}" rpy="0 ${collisions['suspension_angle'] * pi / 180} ${pi if flip else 0}" />
    </collision>
  </link>
  <gazebo reference="${_prefix}suspension">
    <visual>  
      <xacro:element xacro:name="xacro:${material}" />
    </visual> 
  </gazebo>
</xacro:macro>
</robot>