# Weight and inertia is estimated by hand
# CAD needs to be updated, before better values can be obtained 
platform_mass: 15.863
platform_inertia: 
  ixx: 0.17628
  ixy: 0
  ixz: 0
  iyy: 0.33139
  iyz: 0
  izz: 0.40919